pool:
   name: 'Azure Pipelines'
   vmImage: 'vs2017-win2016'

steps:
  - script: |
     choco install ninja
  - script: |
     call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\vc\Auxiliary\build\vcvarsall.bat" x64
     del "C:\ProgramData\chocolatey\bin\c++.exe"
     del "C:\ProgramData\chocolatey\bin\g++.exe"
     del "C:\ProgramData\chocolatey\bin\gcc.exe"
     del "C:\Strawberry\c\bin\c++.exe"
     del "C:\Strawberry\c\bin\g++.exe"
     del "C:\Strawberry\c\bin\gcc.exe"
     cmake -H. -B_build -GNinja -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=C:\artifact -DBUILD_SHARED_LIBS=ON
     cmake --build _build --config debug --target install
